logging:
  file: /applogs/msg-platform/${spring.application.name}.log
  level:
    org: INFO
    com: DEBUG
  register-shutdown-hook: false

#服务注册
eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

#feign远程调用开启熔断
feign:
  hystrix:
    enabled: true

#熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#负载
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    username: admin
    password: 123456
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"