server:
  port: 8107

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

security:
  user:
    name: user
    password: password

spring:
  datasource:
    url: jdbc:mysql://192.168.1.91:3306/test?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
#    password: 123456
    password: Pr0d@1234
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

