server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://192.168.1.91/test?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: Pr0d@1234
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

security:
  user:
    name: user
    password: password
#  oauth2:
#    client:
#      clientId: svca-service
#      clientSecret: ${security.user.password}
#      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
#      grant-type: client_credentials
#      scope: server